// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAGdACbXiGUeqP5QIfXZwjALfPf628t--o',
    appId: '1:72176299647:android:dc44e71bb5e6fb9003594a',
    messagingSenderId: '72176299647',
    projectId: 'lab08-firebase098',
    storageBucket: 'lab08-firebase098.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCiRQW5YA3X5ISTsU1NXpXuoE4INJdzUNE',
    appId: '1:72176299647:ios:a78bd9d724e6b54003594a',
    messagingSenderId: '72176299647',
    projectId: 'lab08-firebase098',
    storageBucket: 'lab08-firebase098.appspot.com',
    iosClientId: '72176299647-7g1v39alehs8oilt7k0i7en4fjfo9kbt.apps.googleusercontent.com',
    iosBundleId: 'com.example.lab08',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCiRQW5YA3X5ISTsU1NXpXuoE4INJdzUNE',
    appId: '1:72176299647:ios:a78bd9d724e6b54003594a',
    messagingSenderId: '72176299647',
    projectId: 'lab08-firebase098',
    storageBucket: 'lab08-firebase098.appspot.com',
    iosClientId: '72176299647-7g1v39alehs8oilt7k0i7en4fjfo9kbt.apps.googleusercontent.com',
    iosBundleId: 'com.example.lab08',
  );
}
